[project]
name = "ipbookplatform-environment"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "ipython<9",
    "jupyter==1.1.1",
    "octave-kernel==0.36.0",
]

[dependency-groups]
dev = [
    "exceptiongroup==1.2.2",
    "pexpect==4.9.0",
    "tomli==2.2.1",
]
